name = helicopter
depends = player_api
optional_depends = default, creative
description = Es el mismo mod, solo he removido la dependencia de 'biofuel' que resultó siendo un coñazo.
title = Not So Simple Helicopter (faco)
